version: '3'
services:
  mongodb:
    image: mongo
    container_name: mymongodb
    ports:
      - "27017:27017"

  flask-app:
    build:
      context: .
    container_name: myflaskapp
    ports:
      - "5000:5000"
    depends_on:
      - mongodb 
    environment:
      MONGO_URI: mongodb://mongodb:27017/mydatabase  
